<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OCA\\Sharing\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'OCA\\Sharing\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'OCA\\Sharing\\Command\\Create' => $baseDir . '/../lib/Command/Create.php',
    'OCA\\Sharing\\Command\\Delete' => $baseDir . '/../lib/Command/Delete.php',
    'OCA\\Sharing\\Command\\Get' => $baseDir . '/../lib/Command/Get.php',
    'OCA\\Sharing\\Command\\Update' => $baseDir . '/../lib/Command/Update.php',
    'OCA\\Sharing\\Controller\\ApiV1Controller' => $baseDir . '/../lib/Controller/ApiV1Controller.php',
    'OCA\\Sharing\\Exception\\AShareException' => $baseDir . '/../lib/Exception/AShareException.php',
    'OCA\\Sharing\\Exception\\ShareConflictException' => $baseDir . '/../lib/Exception/ShareConflictException.php',
    'OCA\\Sharing\\Exception\\ShareInvalidException' => $baseDir . '/../lib/Exception/ShareInvalidException.php',
    'OCA\\Sharing\\Exception\\ShareInvalidOperationParameterException' => $baseDir . '/../lib/Exception/ShareInvalidOperationParameterException.php',
    'OCA\\Sharing\\Exception\\ShareInvalidPropertiesException' => $baseDir . '/../lib/Exception/ShareInvalidPropertiesException.php',
    'OCA\\Sharing\\Exception\\ShareNotFoundException' => $baseDir . '/../lib/Exception/ShareNotFoundException.php',
    'OCA\\Sharing\\Exception\\ShareOperationNotAllowedException' => $baseDir . '/../lib/Exception/ShareOperationNotAllowedException.php',
    'OCA\\Sharing\\Manager' => $baseDir . '/../lib/Manager.php',
    'OCA\\Sharing\\Migration\\Version1000Date20250929161325' => $baseDir . '/../lib/Migration/Version1000Date20250929161325.php',
    'OCA\\Sharing\\Model\\IShareFeature' => $baseDir . '/../lib/Model/IShareFeature.php',
    'OCA\\Sharing\\Model\\IShareFeatureFilter' => $baseDir . '/../lib/Model/IShareFeatureFilter.php',
    'OCA\\Sharing\\Model\\IShareFeatureModifyProperties' => $baseDir . '/../lib/Model/IShareFeatureModifyProperties.php',
    'OCA\\Sharing\\Model\\IShareRecipientType' => $baseDir . '/../lib/Model/IShareRecipientType.php',
    'OCA\\Sharing\\Model\\IShareRecipientTypeSearch' => $baseDir . '/../lib/Model/IShareRecipientTypeSearch.php',
    'OCA\\Sharing\\Model\\IShareSourceType' => $baseDir . '/../lib/Model/IShareSourceType.php',
    'OCA\\Sharing\\Model\\Share' => $baseDir . '/../lib/Model/Share.php',
    'OCA\\Sharing\\Model\\ShareAccessContext' => $baseDir . '/../lib/Model/ShareAccessContext.php',
    'OCA\\Sharing\\Model\\ShareOwner' => $baseDir . '/../lib/Model/ShareOwner.php',
    'OCA\\Sharing\\Model\\ShareRecipient' => $baseDir . '/../lib/Model/ShareRecipient.php',
    'OCA\\Sharing\\Model\\ShareRecipientSearchResult' => $baseDir . '/../lib/Model/ShareRecipientSearchResult.php',
    'OCA\\Sharing\\Model\\ShareSource' => $baseDir . '/../lib/Model/ShareSource.php',
    'OCA\\Sharing\\Registry' => $baseDir . '/../lib/Registry.php',
    'OCA\\Sharing\\ResponseDefinitions' => $baseDir . '/../lib/ResponseDefinitions.php',
);
