<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitSharing
{
    public static $prefixLengthsPsr4 = array (
        'O' =>
        array (
            'OCA\\Sharing\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Sharing\\' =>
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\Sharing\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
        'OCA\\Sharing\\Capabilities' => __DIR__ . '/..' . '/../lib/Capabilities.php',
        'OCA\\Sharing\\Command\\Create' => __DIR__ . '/..' . '/../lib/Command/Create.php',
        'OCA\\Sharing\\Command\\Delete' => __DIR__ . '/..' . '/../lib/Command/Delete.php',
        'OCA\\Sharing\\Command\\Get' => __DIR__ . '/..' . '/../lib/Command/Get.php',
        'OCA\\Sharing\\Command\\Update' => __DIR__ . '/..' . '/../lib/Command/Update.php',
        'OCA\\Sharing\\Controller\\ApiV1Controller' => __DIR__ . '/..' . '/../lib/Controller/ApiV1Controller.php',
        'OCA\\Sharing\\Exception\\AShareException' => __DIR__ . '/..' . '/../lib/Exception/AShareException.php',
        'OCA\\Sharing\\Exception\\ShareConflictException' => __DIR__ . '/..' . '/../lib/Exception/ShareConflictException.php',
        'OCA\\Sharing\\Exception\\ShareInvalidException' => __DIR__ . '/..' . '/../lib/Exception/ShareInvalidException.php',
        'OCA\\Sharing\\Exception\\ShareInvalidOperationParameterException' => __DIR__ . '/..' . '/../lib/Exception/ShareInvalidOperationParameterException.php',
        'OCA\\Sharing\\Exception\\ShareInvalidPropertiesException' => __DIR__ . '/..' . '/../lib/Exception/ShareInvalidPropertiesException.php',
        'OCA\\Sharing\\Exception\\ShareNotFoundException' => __DIR__ . '/..' . '/../lib/Exception/ShareNotFoundException.php',
        'OCA\\Sharing\\Exception\\ShareOperationNotAllowedException' => __DIR__ . '/..' . '/../lib/Exception/ShareOperationNotAllowedException.php',
        'OCA\\Sharing\\Manager' => __DIR__ . '/..' . '/../lib/Manager.php',
        'OCA\\Sharing\\Migration\\Version1000Date20250929161325' => __DIR__ . '/..' . '/../lib/Migration/Version1000Date20250929161325.php',
        'OCA\\Sharing\\Model\\IShareFeature' => __DIR__ . '/..' . '/../lib/Model/IShareFeature.php',
        'OCA\\Sharing\\Model\\IShareFeatureFilter' => __DIR__ . '/..' . '/../lib/Model/IShareFeatureFilter.php',
        'OCA\\Sharing\\Model\\IShareFeatureModifyProperties' => __DIR__ . '/..' . '/../lib/Model/IShareFeatureModifyProperties.php',
        'OCA\\Sharing\\Model\\IShareRecipientType' => __DIR__ . '/..' . '/../lib/Model/IShareRecipientType.php',
        'OCA\\Sharing\\Model\\IShareRecipientTypeSearch' => __DIR__ . '/..' . '/../lib/Model/IShareRecipientTypeSearch.php',
        'OCA\\Sharing\\Model\\IShareSourceType' => __DIR__ . '/..' . '/../lib/Model/IShareSourceType.php',
        'OCA\\Sharing\\Model\\Share' => __DIR__ . '/..' . '/../lib/Model/Share.php',
        'OCA\\Sharing\\Model\\ShareAccessContext' => __DIR__ . '/..' . '/../lib/Model/ShareAccessContext.php',
        'OCA\\Sharing\\Model\\ShareOwner' => __DIR__ . '/..' . '/../lib/Model/ShareOwner.php',
        'OCA\\Sharing\\Model\\ShareRecipient' => __DIR__ . '/..' . '/../lib/Model/ShareRecipient.php',
        'OCA\\Sharing\\Model\\ShareRecipientSearchResult' => __DIR__ . '/..' . '/../lib/Model/ShareRecipientSearchResult.php',
        'OCA\\Sharing\\Model\\ShareSource' => __DIR__ . '/..' . '/../lib/Model/ShareSource.php',
        'OCA\\Sharing\\Registry' => __DIR__ . '/..' . '/../lib/Registry.php',
        'OCA\\Sharing\\ResponseDefinitions' => __DIR__ . '/..' . '/../lib/ResponseDefinitions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitSharing::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitSharing::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitSharing::$classMap;

        }, null, ClassLoader::class);
    }
}
